stages:
  - test

.unit: &unit
  script:
    - tox
  before_script:
    - python -V
    - pip install tox
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - coverage_html_report/
    expire_in: 1 week

test-python37:
  <<: *unit
  image: python:3.7
  stage: test